apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: web-ui
  template:
    metadata:
      labels:
        app: web-ui
    spec:
      containers:
      - image: nginx:latest
        name: web-ui
        ports:
        - containerPort: 80